site_url: https://pppf24.github.io/hse-dashboard/
use_directory_urls: false
site_name: 化工物流HSE工作看板
site_author: 安全环保部（合规管理部）
theme: material

nav:
  - 首页: index.md
  - 任务看板:
    - 2025年12月: tasks/2025-12.md  # <- 新增行
